{{- if (and .Values.ingress.enabled .Values.ingress.certificate.enabled) -}}
{{- range .Values.ingress.tls }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .secretName }}
spec:
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .secretName }}
{{- end }}
{{- end }}
